[theme.options]
stealth_mode = false
fg_image = ""
bg_color = "white"
bg_image = ""
bg_anim_image = ""
font_sizes = [ 10, 8, 8, 32, 25, 4,]
font = "DejaVuSansMono"
font_bold = "DejaVuSansMono-Bold.ttf"
status_font = "DejaVuSansMono"
font_awesome = "font-awesome-solid.otf"
size_offset = 5
label_spacing = 9
cursor = "❤"
friend_bars = "▌"
friend_no_bars = "│"
main_text_color = [ "black",]
color_mode = [ "P", "P",]

[theme.widget.face]
position = [ 13, 40,]
text_font_size = "Huge"
color = [ "lime",]
icon = false
icon_color = true
mask = true
refine = 150
image_type = "png"
f_awesome = false
f_awesome_size = 40
zoom = 1
z_axis = 102
alpha = true
