[theme]

[theme.dev]

[theme.options]

stealth_mode = false
fg_image = ''
bg_color = 'yellow'
bg_image = 'bg-200x200.png'
bg_anim_image = 'bg-200x200.gif'
# Bold, BoldSmall, Medium, Huge, BoldBig, Small
font_sizes = [10, 8, 8, 32, 25, 4]
font = 'DejaVuSansMono'
font_bold = 'DejaVuSansMono-Bold.ttf'
status_font = 'DejaVuSansMono'
font_awesome = 'font-awesome-solid.otf'
size_offset = 5
label_spacing = 9

cursor = '❤'
friend_bars = '▌'
friend_no_bars = '│'

# if the full color or animated full color is enabled
# the main color will have priority on all text color
main_text_color = []

# To define which type of image will be saved 
# 1, L, P, RGB, RGBA, LAB,...
color_mode = ['P', 'P']

[theme.widget]

[theme.widget.face]
position = [13, 50]
text_font_size = "Huge"
color = ['black']
icon = true
icon_color = false
mask = false
refine = 150
image_type = 'png'
f_awesome = false
f_awesome_size = 40
zoom = 0.5
z_axis = 102

[theme.widget.name]
position = [8,130]
text_font_size = "Bold"
color = ['red', 'black']
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.channel]
position = [10, 158]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
color = ['black']
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 100

[theme.widget.aps]
position = [126, 25]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
color = ['black']
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 101

[theme.widget.uptime]
position = [2, 20]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
color = ['black']
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.line1]
position = [0, -10, 255, -10]
color = ['black','blue']
z_axis = -1

[theme.widget.line2]
position = [0, -10, 240, -10]
color = ['black']
z_axis = -1

[theme.widget.friend_face]
position = [140, 20]
text_font_size = "Huge"
color = ['black']
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.friend_name]
position = [150, 18]
text_font_size = "Medium"
color = ['black']
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.shakes]
position = [5, 180]
label = ""
label_font_size = "Bold"
text_font_size = "Medium"
label_spacing = 9
color = ['black']
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.mode]
position = [35, 45]
text_font_size = "Bold"
color = ['black']
icon = false
z_axis = 0

[theme.widget.status]
position = [47, 150]
text_font = 'DejaVuSansMono'
size_offset = 5
text_font_size = "Small"
color = ['black']
wrap = true
max_length = 20
z_axis = 0

[theme.widget.memtemp_cpu]
position = [3,5]
color = ['black']
label = ''
label_font_size = 'Bold'
text_font_size = 'Medium'
label_spacing = 9
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.memtemp_mem]
position = [34,5]
color = ['black']
label = ''
label_font_size = 'Bold'
text_font_size = 'Medium'
label_spacing = 9
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.memtemp_temp]
position = [64,5]
color = ['black']
label = ''
label_font_size = 'Bold'
text_font_size = 'Medium'
label_spacing = 9
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.bluetooth]
position = [280, 170]
label = 'BT'
label_font_size = 'Bold'
text_font_size = 'Medium'
label_spacing = 9
color = ['black']
icon = false
f_awesome = true
f_awesome_size = 40
z_axis = 104