[theme.options]
stealth_mode = false
fg_image = ""
bg_color = [ 0, 0, 0, 100,]
bg_image = ""
bg_anim_image = ""
font_sizes = [ 10, 8, 10, 50, 25, 9,]
font = "DejaVuSansMono"
font_bold = "DejaVuSansMono-Bold"
status_font = "DejaVuSansMono"
font_awesome = ""
size_offset = 5
label_spacing = 9
cursor = "❤"
friend_bars = "▌"
friend_no_bars = "│"
main_text_color = [ "lime",]
color_mode = [ "P", "P",]

[theme.widget.channel]
position = [ 0, 0,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Medium"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "CH"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 0
f_awesome = false
f_awesome_size = 0
widget_type = "LabeledValue"

[theme.widget.aps]
position = [ 80, 0,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Medium"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "APS"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 0
f_awesome = false
f_awesome_size = 0
widget_type = "LabeledValue"

[theme.widget.uptime]
position = [ 240, 0,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Medium"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "UP"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 0
f_awesome = false
f_awesome_size = 0
widget_type = "LabeledValue"

[theme.widget.line1]
position = [ 0, 14, 320, 0,]
color = [ "#000000",]
z_axis = 0
width = 1
widget_type = "Line"

[theme.widget.line2]
position = [ 0, 220, 320, 0,]
color = [ "#000000",]
z_axis = 0
width = 1
widget_type = "Line"

[theme.widget.face]
position = [ 35, 50,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Huge"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0
widget_type = "Text"

[theme.widget.friend_face]
position = [ 0, 130,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Bold"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0
widget_type = "Text"

[theme.widget.friend_name]
position = [ 40, 135,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "BoldSmall"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0
widget_type = "Text"

[theme.widget.name]
position = [ 5, 20,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Bold"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0
widget_type = "Text"

[theme.widget.status]
position = [ 80, 160,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Small"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = true
max_length = 0
widget_type = "Text"

[theme.widget.shakes]
position = [ 0, 220,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Medium"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "PWND "
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 0
f_awesome = false
f_awesome_size = 0
widget_type = "LabeledValue"

[theme.widget.mode]
position = [ 280, 220,]
color = [ "#000000",]
z_axis = 0
text_font = ""
text_font_size = "Bold"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
image_type = "png"
wrap = false
max_length = 0
widget_type = "Text"

[theme.widget.bluetooth]
position = [ 145, 0,]
color = [ 262144,]
z_axis = 0
text_font = ""
text_font_size = "Medium"
size_offset = 0
icon = false
icon_color = false
invert = false
alpha = false
mask = false
refine = 150
zoom = 1
label = "BT"
label_font = ""
label_font_size = "Medium"
label_spacing = 5
label_line_spacing = 0
f_awesome = false
f_awesome_size = 0
widget_type = "LabeledValue"
