[theme.options]
stealth_mode = false
fg_image = ""
bg_color = "black"
bg_image = "bg-250x122.png"
bg_anim_image = ""
font_sizes = [ 9, 3, 9, 30, 9, 11,]
font = "DejaVuSansMono"
font_bold = "DejaVuSansMono-Bold"
status_font = "DejaVuSansMono"
font_awesome = ""
size_offset = 6
label_spacing = 9
cursor = "❤"
friend_bars = "▌"
friend_no_bars = "│"
main_text_color = [ "black",]
color_mode = [ "P", "P",]

[theme.widget.face]
position = [ 10, 32,]
text_font_size = "Huge"
color = [ "lime",]
icon = true
icon_color = true
mask = false
refine = 150
image_type = "png"
f_awesome = false
f_awesome_size = 40
zoom = 1
z_axis = 102

[theme.widget.name]
position = [ 5, 11,]
text_font_size = "Medium"
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.channel]
position = [ 86, 11,]
label = "CH:"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 14
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.aps]
position = [ 201, 11,]
label = "AP:"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 0
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = true
f_awesome_size = 20
z_axis = 0

[theme.widget.uptime]
position = [ 134, 11,]
label = "UP:"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 7
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40

[theme.widget.line1]
position = [ 0, -12, 242, -12,]
color = [ "lime",]
z_axis = 0

[theme.widget.line2]
position = [ 0, -12, 242, -12,]
color = [ "lime",]
z_axis = 0

[theme.widget.friend_face]
position = [ 86, 100,]
text_font_size = "Huge"
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.friend_name]
position = [ 88, 100,]
text_font_size = "Medium"
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.shakes]
position = [ 86, 55,]
label = "PWND: "
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 2
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.mode]
position = [ 227, 0,]
text_font_size = "Medium"
color = [ "lime",]
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.status]
position = [ 86, 68,]
text_font_size = "BoldSmall"
color = [ "lime",]
wrap = true
max_length = 20
size_offset = 6
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.bluetooth]
position = [ 201, 0,]
label = "BT"
label_font_size = "BoldBig"
text_font_size = "BoldBig"
label_spacing = 2
label_line_spacing = 0
color = [ "lime",]
icon = false
f_awesome = true
f_awesome_size = 40
z_axis = 0

[theme.widget.altitude]
position = [ 91, 42,]
color = [ "lime",]
label = "alt:"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 4
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.longitude]
position = [ 86, 32,]
color = [ "lime",]
label = "long:"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 4
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.latitude]
position = [ 91, 22,]
color = [ "lime",]
label = "lat:"
label_font_size = "Medium"
text_font_size = "Medium"
label_spacing = 4
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0

[theme.widget.display-password]
position = [ 3, 106,]
color = [ "lime",]
label = ""
label_font_size = "Small"
text_font_size = "Small"
label_spacing = 0
label_line_spacing = 0
icon = false
f_awesome = false
f_awesome_size = 40
z_axis = 0
